# Generated by Django 4.0.4 on 2022-05-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='illuminance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
