# Generated by Django 4.0.4 on 2022-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='humidity',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='image',
            field=models.ImageField(default=None, upload_to='media/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='is_turn_on',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='watering_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GardenManagement',
        ),
    ]
