# Generated by Django 4.0.4 on 2022-05-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_humidity_garden_image_garden_is_turn_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary/%Y/%m/%d')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
        ),
    ]
