# Generated by Django 4.0.4 on 2022-06-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_alter_garden_image_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='is_temi_ready',
            field=models.BooleanField(default=False),
        ),
    ]
