# Generated by Django 4.0.4 on 2022-06-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_garden_is_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='is_temi_ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garden',
            name='is_water',
            field=models.IntegerField(default=0),
        ),
    ]
